### ISSUE TITLE
ResolveUrl doesn't support mp4cloud

### ISSUE THREAD

**Issue by Nonononoki** [jsergio123/script.module.resolveurl#118]
Would it be possible to add support for mp4cloud?

```
video_url: https://player.mp4cloud.net/mp4yup.php?id=V5s5N0i4pd82
2019-05-22 19:19:53.184 T:10568   DEBUG: ResolveURL: Relevant Resolvers: []
2019-05-22 19:19:53.185 T:10568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'bool' objects
                                            Traceback (most recent call last):
                                              File "C:\Users\Nono\AppData\Roaming\Kodi\addons\org.nonononoki.justdubs\addon.py", line 432, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Nono\AppData\Roaming\Kodi\addons\org.nonononoki.justdubs\addon.py", line 424, in router
                                                play_video(params['url'])
                                              File "C:\Users\Nono\AppData\Roaming\Kodi\addons\org.nonononoki.justdubs\addon.py", line 328, in play_video
                                                print('direct link: ' + stream_url)
                                            TypeError: cannot concatenate 'str' and 'bool' objects
                                            -->End of Python script error report<--
```

**Comment by Gujal00** [comment]
mp4cloud is just embedding mp4upload links
Just rebuild the url
For e.g.,
```https://player.mp4cloud.net/mp4upload.php?id=dlay4swac022```
rewrite as
```https://www.mp4upload.com/embed-dlay4swac022.html```
before sending to SMR

**Comment by Nonononoki** [comment]
@Gujal00 Are you sure that it always work?
Doesn't work for the following example:
https://player.mp4cloud.net/mp4yup.php?id=LYrJxt78x71U (works)
https://www.mp4upload.com/embed-LYrJxt78x71U.html (doesn't work)

**Comment by Nonononoki** [comment]
> 
> 
> mp4cloud is just embedding mp4upload links
> Just rebuild the url
> For e.g.,
> `https://player.mp4cloud.net/mp4upload.php?id=dlay4swac022`
> rewrite as
> `https://www.mp4upload.com/embed-dlay4swac022.html`
> before sending to SMR

The problem is that mp4cloud embeds links form different hosters, such as mp4space and more (mp4yup in the log for example)

**Comment by Gujal00** [comment]
Yes parsing and pulling embeds is not a function of SMR. You need to do that in the addon and pass the actual hoster embed to SMR.
```https://player.mp4cloud.net/mp4space.php?id=110065971```
can be rewritten as
```https://player.mp4cloud.net/mp4space2.php?id=110065971``` and then look in the page source for 
```
<video id="video_player" class="video-js vjs-big-play-centered video-dynamic-center" controls preload="none" poster="https://a4-images.myspacecdn.com/images04/1/abc1d9d5a9fd430d88784cd11ebe6d82/full.jpg" data-setup='{"techOrder": ["html5", "flash"]}'>
        <source src="https://l-videos.myspacecdn.com:443/videos01/4/6752ed52a8ec4b6989a7fe95e2f86996/vid.mp4?t=1561110858_145acc55c7177ab6850ed92f438b964b" type='video/mp4' label='720p' res='720'/>
        <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
    </video>
```

 Please close this issue as this has nothing to do with SMR
