### ISSUE TITLE
problem with alldebrid

### ISSUE THREAD

**Issue by ic32k** [jsergio123/script.module.resolveurl#146]
When trying to reautorize the alldebrid the resolveurl module crash giving this exception:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/default.py", line 145, in <module>
                                                sys.exit(main())
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/default.py", line 141, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/resolveurl/lib/url_dispatcher.py", line 82, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/default.py", line 83, in auth_ad
                                                if alldebrid.AllDebridResolver().authorize_resolver():
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/alldebrid.py", line 262, in authorize_resolver
                                                js_result = self.net.http_GET(url, headers=self.headers).content
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/resolveurl/lib/net.py", line 213, in http_GET
                                                return self._fetch(url, headers=headers, compression=compression)
                                              File "/home/pi/.kodi/addons/script.module.resolveurl/lib/resolveurl/lib/net.py", line 317, in _fetch
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            -->End of Python script error report<--

**Comment by gzenio22** [comment]
I have the same trouble, please help I bought a premium for a month to get tested and here the links do not work

**Comment by jsergio123** [comment]
What version of Kodi are you using? From what I can see from your log snipet is the ssl certificate they are/were using isn't valid. Are you still having this error?

**Comment by gzenio22** [comment]
Kodi 18 The newest stable one yesterday he was still jumping
