### ISSUE TITLE
waaw resolver

### ISSUE THREAD

**Issue by Greenhousecafe** [jsergio123/script.module.resolveurl#16]
Hi,  getting an error when trying to resolve a waaw link (https://waaw.tv/watch_video.php?v=j2xAMKnWp4Ck). Anything you can do please mate?.

 ERROR: ResolveURL: ResolverError Error - From: waaw Link: https://waaw.tv/watch_video.php?v=j2xAMKnWp4Ck: No JSON object could be decoded
20:03:27.437 T:2328   DEBUG: ResolveURL: Traceback (most recent call last):
                                              File "C:\Users\denly\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 180, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "C:\Users\denly\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\waaw.py", line 101, in get_media_url
                                                raise ResolverError(e)
                                            ResolverError: No JSON object could be decoded

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/4f8d009944b2b3fca28dcab33557974e7c0ec43b
