### ISSUE TITLE
Not an isuue but need help @Gujal00

### ISSUE THREAD

**Issue by jigoop1** [jsergio123/script.module.resolveurl#300]
@Gujal00 
in deccandelight new update give this error when open apnetv.py or yaartv.py scarper
it only give this error for this "India’s Best Dancer" show other shows work
resolver return this link so need somewhere encode('utf-8')
> video[1]  https://cdn1.apnevideotwo.co/apnevideoone/2019/March/21st/India’s Best Dancer 21st March 2020.mp4/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yMi8yMDIwIDE6NTM6MTAgUE0maGFzaF92YWx1ZT1OZW5sTTExSTBJUkF1aytOcWlPL1FnPT0mdmFsaWRtaW51dGVzPTEyMCZpZD0xYzg4ZDQ1Mzc3NDNmZTkwMDBlMWQ5ZGNjNjQwZmExMA==|Origin=https%3A%2F%2Fapnevideoone.co 

>      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.KeyError'>
    Error Contents: u'\u2019'
    Traceback (most recent call last):
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.deccandelight\main.py", line 25, in <module>
        deccandelight.router(sys.argv[2][1:])
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.deccandelight\resources\lib\deccandelight.py", line 709, in router
        list_videos(params['site'], params['title'], params['iurl'], params['thumb'])
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.deccandelight\resources\lib\deccandelight.py", line 371, in list_videos
        url = '{0}?action=9&iurl={1}'.format(_url, urllib.quote_plus(video[1]))
      File "C:\Program Files\Kodi_19\system\python\Lib\urllib.py", line 1304, in quote_plus
        s = quote(s, safe + ' ')
      File "C:\Program Files\Kodi_19\system\python\Lib\urllib.py", line 1299, in quote
        return ''.join(map(quoter, s))
    KeyError: u'\u2019'

>

**Comment by Gujal00** [comment]
@jigoop1 Please do not post non SMR stuff in this git
If you need to contact me use https://keybase.io/gujal
