### ISSUE TITLE
Error resolving Google drive links in Kodi 19

### ISSUE THREAD

**Issue by TitanKodi** [jsergio123/script.module.resolveurl#377]
When I try to resolve any Google drive link in Kodi 19, I get this error:
`source_url = source_url.decode('unicode_escape')  AttributeError: 'str' object has no attribute 'decode'`

It could be solved by replacing line 212 of googlevideo.py with: 
`source_url = source_url.encode().decode("unicode-escape")`

**Comment by Gujal00** [comment]
@TitanKodi 
I think https://github.com/jsergio123/script.module.resolveurl/commit/31a6c9043b53940c69b3643fbd79c6d20a410c55 will fix this issue, can you try and report please

**Comment by TitanKodi** [comment]
@Gujal00 
It doesn't seem to work, with all the links I have working; gives me error File Not Found; I attach the error of the log:
`2020-11-02 09:29:35.212 T:22376   ERROR <general>: ResolveURL: ResolverError Error - From: googlevideo Link: https://drive.google.com/file/d/1wo-YX1J52_bpSOOkU0oS0r36JoEbbv9L/view?usp=sharing: File not found
2020-11-02 09:29:35.222 T:22376   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resolveurl.resolver.ResolverError'>
                                                   Error Contents: File not found
                                                   Traceback (most recent call last):
                                                     File "C:\Users\X\AppData\Roaming\Kodi\addons\plugin.video.X\default.py", line 2853, in <module>
                                                       run()
                                                     File "C:\Users\X\AppData\Roaming\Kodi\addons\plugin.video.X\default.py", line 32, in run
                                                       exec (action+"(params)")
                                                     File "<string>", line 1, in <module>
                                                     File "C:\Users\X\AppData\Roaming\Kodi\addons\plugin.video.X\default.py", line 2768, in resolve_resolveurl
                                                       finalurl = resolveurl . resolve ( params . get ( "url" ) )
                                                     File "C:\Users\X\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 129, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\X\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 187, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\X\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\googlevideo.py", line 90, in get_media_url
                                                       raise ResolverError('File not found')
                                                   resolveurl.resolver.ResolverError: File not found
                                                   -->End of Python script error report<--
                                                   `

**Comment by Gujal00** [comment]
That link works if it has not exceeded playcount for the day
<img src="https://i.imgur.com/JDHyHrT.png">
It all depends if you can play without logging in through a browser
If it has exceeded playcount, nothing can be done. or if it requires login, then the resolverrelies on gdrive addon to play

**Comment by TitanKodi** [comment]
Yes, when I sent you the log message the link it worked in Kodi 18 but in Kodi 19 sent me the error; I also tested with 5 more links (working all) and it also return me the same error

**Comment by Gujal00** [comment]
That screenshot above is from Kodi19. Did you apply all the changes from https://github.com/jsergio123/script.module.resolveurl/commit/31a6c9043b53940c69b3643fbd79c6d20a410c55 before testing?

**Comment by TitanKodi** [comment]
![image](https://user-images.githubusercontent.com/65163693/98274426-b0b15f80-1f93-11eb-91ab-f311ab0b38a3.png)

**Comment by Gujal00** [comment]
Okay so you are testing with the release version. the fix is not released yet and hence I linked you to the git commit to get the latest files for testing

**Comment by Gujal00** [comment]
@TitanKodi v5.1.13 released with the fix, test and report please

**Comment by TitanKodi** [comment]
@Gujal00 with v5.1.13 it works
