### ISSUE TITLE
HTTP Live stream error

### ISSUE THREAD

**Issue by TseClifford** [jsergio123/script.module.resolveurl#560]
There seems to be an issue when trying to play from an HLS source. The link plays fine through a browser but throws an error on Kodi.

ERROR <general>: ResolveURL: AttributeError Error - From: Icdrama Link: http://icdrama.to/vidembed.cYl_9XLclxXNhR9lksfVlw.html: 'bool' object has no attribute 'startswith'
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'AttributeError'>
                 Error Contents: 'bool' object has no attribute 'startswith'
                 Traceback (most recent call last):
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\plugin.video.icdrama\addon.py", line 20, in <module>
                     action_func(**kargs)
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\plugin.video.icdrama\lib\actions.py", line 28, in make_dir
                     diritems = func(*args, **kargs)
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\plugin.video.icdrama\lib\actions.py", line 189, in mirrors
                     return _mirrors(url)
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\plugin.video.icdrama\lib\actions.py", line 204, in _mirrors
                     play_mirror(url)
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\plugin.video.icdrama\lib\actions.py", line 173, in play_mirror
                     vidurl = common.resolve(iframe_url)
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\plugin.video.icdrama\lib\common.py", line 89, in resolve
                     return hmf.resolve()
                   File "C:\Users\XXXXXX\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 188, in resolve
                     if stream_url.startswith("//"):
                 AttributeError: 'bool' object has no attribute 'startswith'
                 -->End of Python script error report<--

**Comment by Gujal00** [comment]
It is an addon issue feeding wrong embeds to Resolveurl, Check with addon developer on what embed is being sent to resolve

**Comment by TseClifford** [comment]
Thanks, will try to resolve the issue on the other end.
