### ISSUE TITLE
streamlare not working 

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#616]
hi guy streamlare not working operand "+" in get media_media_url  
hxxps://streamlare.com/e/9aNdbzk3Rp4z8JjB
this is log error
2022-01-15 12:28:23.093 T:5940    ERROR <general>: ResolveURL: TypeError Error - From: streamlare Link: hxxps://streamlare.com/e/9aNdbzk3Rp4z8JjB: unsupported operand type(s) for +: 'NoneType' and 'str'
2022-01-15 12:28:23.094 T:5940    DEBUG <general>: ResolveURL: Traceback (most recent call last):
                                                     File "C:\Users\PCPRENO1\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 187, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\PCPRENO1\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\streamlare.py", line 43, in get_media_url
                                                       return helpers.pick_source(sources) + helpers.append_headers(headers)
                                                   TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Gujal00** [comment]
They have switched to custom websocket based player. Cant see how to do it for kodi. Broken for now

**Comment by Gujal00** [comment]
I do not think this plugin will be fixed as [they switched to p2p](https://www.wjunction.com/threads/streamlare-com-simple-powerful-video-file-hosting-premium-affiliate-program-event.254434/post-2471564)

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/9902d12f3309eb4784dcc9bcc5c3fc52b8228873

**Comment by soter80** [comment]
Thanks guy

**Comment by dober2** [comment]
Looks like its broken again.
